<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'File name' => 'Имя файла',
    'Alias' => 'Алиас',
    'Alt attribute' => 'Атрибут alt',
    'Changes not saved.' => 'Изменения не сохранены.',
    'Changes saved!' => 'Изменения сохранены!',
    'Created' => 'Создан',
    'Default' => 'По умолчанию',
    'Delete' => 'Удалить',
    'Description' => 'Описание',
    'Do not forget every time you change thumbnails presets to make them resize.' => 'Не забывайте при каждом изменении предустановок миниатюр делать их ресайз.',
    'Do resize thumbnails' => 'Сделать ресайз миниатюр',
    'File manager' => 'Файловый менеджер',
    'Files' => 'Файлы',
    'ID' => 'Идентификатор',
    'If you change the thumbnails sizes, it is strongly recommended to make resize all thumbnails.' => 'Если вы изменили размеры миниатюр, строго рекомендуется сделать ресайз всех миниатюр.',
    'Insert' => 'Вставить',
    'Media File' => 'Медиа-файл',
    'Now using next thumbnails presets' => 'Используемые сейчас наборы миниатюр',
    'Original' => 'Оригинальный',
    'Permission denied.' => 'Доступ запрещен.',
    'Save' => 'Сохранить',
    'Settings' => 'Настройки',
    'Size' => 'Размер',
    'Thumbnails settings' => 'Настройки миниатюр',
    'Thumbnails sizes has been resized successfully!' => 'Размеры миниатюр успешно изменены!',
    'Type' => 'Тип',
    'Updated' => 'Обновлён',
    'Upload' => 'Загрузить',
    'Upload manager' => 'Менеджер загрузок',
    'Url' => 'Ссылка',
];
