<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Alias' => '',
    'Alt attribute' => '',
    'Back to gallery' => '',
    'Can\'t to save so small image.' => '',
    'Changes not saved.' => '',
    'Changes saved!' => '',
    'Created' => '',
    'Default' => '',
    'Delete' => '',
    'Description' => '',
    'Do not forget every time you change thumbnails presets to make them resize.' => '',
    'Do resize thumbnails' => '',
    'Edit' => '',
    'File manager' => '',
    'File name' => '',
    'Files' => '',
    'ID' => '',
    'If you change the thumbnails sizes, it is strongly recommended to make resize all thumbnails.' => '',
    'Incorrect cropper borders. Please, check it.' => '',
    'Insert' => '',
    'Media File' => '',
    'Now using next thumbnails presets' => '',
    'Original' => '',
    'Permission denied.' => '',
    'Rotate left' => '',
    'Rotate right' => '',
    'Save' => '',
    'Settings' => '',
    'Size' => '',
    'This file already exists.' => '',
    'Thumbnails settings' => '',
    'Thumbnails sizes has been resized successfully!' => '',
    'Type' => '',
    'Updated' => '',
    'Url' => '',
];
