<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Alias' => '',
    'Can\'t to save so small image.' => '',
    'Cancel' => '',
    'Changes not saved' => '',
    'Changes saved' => '',
    'Created at' => '',
    'Default' => '',
    'Delete forever' => '',
    'Edit' => '',
    'File name' => '',
    'ID' => '',
    'Media File' => '',
    'Permission denied.' => '',
    'Rotate left' => '',
    'Rotate right' => '',
    'Showing files <b>0</b> of <b>0</b>.' => '',
    'Showing files <b>{begin, number}-{end, number}</b> of <b>{totalCount, number}</b>.' => '',
    'Size' => '',
    'This file already exists.' => '',
    'Updated at' => '',
    'Upload files' => '',
    'Created' => 'Izveidots',
    'Description' => 'Faila apraksts',
    'Do not forget every time you change thumbnails presets to make them resize.' => 'Neaizmirsti to, ka pēc katra sīkattēlu sākotnējo uzstādījumu maiņas ir jāveic sīkattēlu mērogošana.',
    'Do resize thumbnails' => 'Veikt sīkattēlu mērogošanu',
    'File manager' => 'Failu menedžers',
    'Files' => 'Faili',
    'If you change the thumbnails sizes, it is strongly recommended to make resize all thumbnails.' => 'Ja ir ticis mainīts sikattēlu izmērs, ir ieteicams vēlreiz veikt visu attēlu mērogošanu.',
    'Now using next thumbnails presets' => 'Šobrīd izmantotais komplekts ar sīkattēliem',
    'Original' => 'Oriģinālais',
    'Save' => 'Saglabāt',
    'Settings' => 'Uzstādījumi',
    'Thumbnails settings' => 'Sīkattēlu uzstādījumi',
    'Thumbnails sizes has been resized successfully!' => 'Sīkattēlu izmēri tika sekmīgi izmainīti!',
    'Type' => 'Tips',
    'Updated' => 'Atjaunināts',
    'Url' => 'URL saite',
];
