<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Alias' => '',
    'Default' => '',
    'File name' => '',
    'ID' => '',
    'Media File' => '',
    'Permission denied.' => '',
    'Size' => '',
    'This file already exists.' => '',
    'Upload' => '',
    'Alt attribute' => 'ALT属性',
    'Changes not saved.' => '修改没有保存。',
    'Changes saved!' => '修改已保存!',
    'Created' => '创建',
    'Delete' => '删除',
    'Description' => '描述',
    'Do not forget every time you change thumbnails presets to make them resize.' => '你每一次调整缩略图预设，不要忘记重设它们的尺寸。',
    'Do resize thumbnails' => '改变缩略图大小',
    'File manager' => '文件管理',
    'Files' => '文件',
    'If you change the thumbnails sizes, it is strongly recommended to make resize all thumbnails.' => '如果你改变缩略图的大小，强烈建议调整所有缩略图。',
    'Insert' => '插入',
    'Now using next thumbnails presets' => '现在使用下一个预设缩略图',
    'Original' => '原',
    'Save' => '保存',
    'Settings' => '设置',
    'Thumbnails settings' => '缩略图设置',
    'Thumbnails sizes has been resized successfully!' => '缩略图大小已成功修改!',
    'Type' => '类型',
    'Updated' => '更新',
    'Upload manager' => '上传管理',
    'Url' => '链接地址',
];
