<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Alias' => '',
    'Are you sure you want to delete this file?' => '',
    'Can\'t to save so small image.' => '',
    'Cancel' => '',
    'Changes not saved' => '',
    'Changes saved' => '',
    'Created at' => '',
    'Default' => '',
    'Delete forever' => '',
    'Edit' => '',
    'File name' => '',
    'ID' => '',
    'Media File' => '',
    'Permission denied.' => '',
    'Rotate left' => '',
    'Rotate right' => '',
    'Showing files <b>0</b> of <b>0</b>.' => '',
    'Showing files <b>{begin, number}-{end, number}</b> of <b>{totalCount, number}</b>.' => '',
    'Size' => '',
    'This file already exists.' => '',
    'Updated at' => '',
    'Upload files' => '',
    'Created' => 'Tạo mới',
    'Description' => 'Mô tả',
    'Do not forget every time you change thumbnails presets to make them resize.' => 'Đừng quên mỗi khi bạn thay đổi cài đặt trước của hình thu nhỏ để làm cho chúng thay đổi kích thước.',
    'Do resize thumbnails' => 'Đồng ý thay đổi kích thước hình thu nhỏ',
    'File manager' => 'Quản lí File',
    'Files' => 'File',
    'If you change the thumbnails sizes, it is strongly recommended to make resize all thumbnails.' => 'Nếu bạn thay đổi kích thước hình thu nhỏ, nó được khuyến khích để thực hiện thay đổi kích thước tất cả các hình thu nhỏ.',
    'Now using next thumbnails presets' => 'Bây giờ sử dụng cài đặt trước cho hình thu nhỏ tiếp theo',
    'Original' => 'Nguyên bản',
    'Save' => 'Lưu lại',
    'Settings' => 'Cài đặt',
    'Thumbnails settings' => 'Cài đặt hình thu nhỏ',
    'Thumbnails sizes has been resized successfully!' => 'Kích thước hình thu nhỏ đã đưuọc thay đổi thành công!',
    'Type' => 'Kiểu',
    'Updated' => 'Cập nhật',
    'Url' => 'Đường dẫn',
];
