<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Alias' => '',
    'Default' => '',
    'File name' => '',
    'ID' => '',
    'Media File' => '',
    'Permission denied.' => '',
    'Size' => '',
    'Upload' => '',
    'Alt attribute' => 'attributo alt',
    'Changes not saved.' => 'Alterações não foram guardadas.',
    'Changes saved!' => 'Alterações guardadas!',
    'Created' => 'Criado',
    'Delete' => 'Apagar',
    'Description' => 'Descrição',
    'Do not forget every time you change thumbnails presets to make them resize.' => 'Não se esqueça que sempre que alterar os tamanhos das miniaturas deve-as redimensionar.',
    'Do resize thumbnails' => 'Redimensionar as miniaturas',
    'File manager' => 'Gestor de ficheiros',
    'Files' => 'Ficheiros',
    'If you change the thumbnails sizes, it is strongly recommended to make resize all thumbnails.' => 'Se alterar o tamanho das miniaturas, é fortemente recomendável que redimensione todas as miniaturas.',
    'Insert' => 'Inserir',
    'Now using next thumbnails presets' => 'Agora usando os seguintes tamanhos de miniaturas',
    'Original' => 'Original',
    'Save' => 'Guardar',
    'Settings' => 'Definições',
    'Thumbnails settings' => 'Definições de miniaturas',
    'Thumbnails sizes has been resized successfully!' => 'As miniaturas foram redimensionadas com sucesso!',
    'Type' => 'Typo',
    'Updated' => 'Atualizado',
    'Upload manager' => 'Enviar ficheiros',
    'Url' => 'Url',
];
